name: Premier test CI

on:
  push:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Afficher un message
        run: echo "Bonjour depuis mon runner self-hosted"

      - name: Afficher le dossier courant
        run: pwd

      - name: Lister les fichiers
        run: ls -la
